import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { obj, Post } from "@/domain/models/Post";

export default function Home() {
    console.log('%c LOG Post', 'background: #222; color: #bada55', obj);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        NextJS App
    </>
  )
}
